In [1]:
import pandas as pd

shipdf=pd.read_csv("unclean_data_ship.csv")
shipdf.describe()
print("Columns:",shipdf.columns)
print("Rows : ",len(shipdf))
print(type(shipdf))
print(shipdf.head())
shipdf

Columns: Index(['Order ID', 'consumer_first_class', 'consumer_same_day',
       'consumer_second_class', 'consumer_standard_class', 'consumer_total',
       'corporate_first_class', 'corporate_same_day', 'corporate_second_class',
       'corporate_standard_class', 'corporate_total',
       'home_office_first_class', 'home_office_same_day',
       'home_office_second_class', 'home_office_standard_class',
       'home_office_total'],
      dtype='object')
Rows :  823
<class 'pandas.core.frame.DataFrame'>
         Order ID  consumer_first_class  consumer_same_day  \
0  CA-2011-100293                   NaN                NaN
1  CA-2011-100706                   NaN                NaN
2  CA-2011-100895                   NaN                NaN
3  CA-2011-100916                   NaN                NaN
4  CA-2011-101266                   NaN                NaN

   consumer_second_class  consumer_standard_class  consumer_total  \
0                    NaN                      NaN             NaN
1                 129.44                      NaN          129.44
2                    NaN                   605.47          605.47
3                    NaN                      NaN             NaN
4                  13.36                      NaN           13.36

   corporate_first_class  corporate_same_day  corporate_second_class  \
0                    NaN                 NaN                     NaN
1                    NaN                 NaN                     NaN
2                    NaN                 NaN                     NaN
3                    NaN                 NaN                     NaN
4                    NaN                 NaN                     NaN

   corporate_standard_class  corporate_total  home_office_first_class  \
0                       NaN              NaN                      NaN
1                       NaN              NaN                      NaN
2                       NaN              NaN                      NaN
3                    788.86           788.86                      NaN
4                       NaN              NaN                      NaN

   home_office_same_day  home_office_second_class  home_office_standard_class  \
0                   NaN                       NaN                      91.056
1                   NaN                       NaN                         NaN
2                   NaN                       NaN                         NaN
3                   NaN                       NaN                         NaN
4                   NaN                       NaN                         NaN

   home_office_total
0             91.056
1                NaN
2                NaN
3                NaN
4                NaN

,Order ID,consumer_first_class,consumer_same_day,consumer_second_class,consumer_standard_class,consumer_total,corporate_first_class,corporate_same_day,corporate_second_class,corporate_standard_class,corporate_total,home_office_first_class,home_office_same_day,home_office_second_class,home_office_standard_class,home_office_total
0,CA-2011-100293,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91.0560,91.0560
1,CA-2011-100706,NaN,NaN,129.4400,NaN,129.440,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CA-2011-100895,NaN,NaN,NaN,605.4700,605.470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CA-2011-100916,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,788.8600,788.8600,NaN,NaN,NaN,NaN,NaN
4,CA-2011-101266,NaN,NaN,13.3600,NaN,13.360,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,US-2014-166611,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68.7420,68.7420,NaN,NaN,NaN,NaN,NaN
819,US-2014-167920,NaN,NaN,1827.5100,NaN,1827.510,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
820,US-2014-168116,NaN,NaN,NaN,NaN,NaN,NaN,8167.420,NaN,NaN,8167.4200,NaN,NaN,NaN,NaN,NaN
821,US-2014-168690,NaN,NaN,NaN,2.8080,2.808,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
822,Grand Total,20802.173,8132.409,49724.2545,116922.1345,195580.971,20792.607,9907.308,35243.231,55942.7865,121885.9325,7737.786,2977.456,8791.127,54748.6325,74255.0015

In [3]:
import pandas as pd

print(shipdf)
shipdf=pd.melt(shipdf,
               ship_m=["Ship Mode"],
               Ord_id=["Order ID"],
               sales=["Sales"]
               )
print(shipdf)

           Order ID  consumer_first_class  consumer_same_day  \
0    CA-2011-100293                   NaN                NaN
1    CA-2011-100706                   NaN                NaN
2    CA-2011-100895                   NaN                NaN
3    CA-2011-100916                   NaN                NaN
4    CA-2011-101266                   NaN                NaN
..              ...                   ...                ...
818  US-2014-166611                   NaN                NaN
819  US-2014-167920                   NaN                NaN
820  US-2014-168116                   NaN                NaN
821  US-2014-168690                   NaN                NaN
822     Grand Total             20802.173           8132.409

     consumer_second_class  consumer_standard_class  consumer_total  \
0                      NaN                      NaN             NaN
1                 129.4400                      NaN         129.440
2                      NaN                 605.4700         605.470
3                      NaN                      NaN             NaN
4                  13.3600                      NaN          13.360
..                     ...                      ...             ...
818                    NaN                      NaN             NaN
819              1827.5100                      NaN        1827.510
820                    NaN                      NaN             NaN
821                    NaN                   2.8080           2.808
822             49724.2545              116922.1345      195580.971

     corporate_first_class  corporate_same_day  corporate_second_class  \
0                      NaN                 NaN                     NaN
1                      NaN                 NaN                     NaN
2                      NaN                 NaN                     NaN
3                      NaN                 NaN                     NaN
4                      NaN                 NaN                     NaN
..                     ...                 ...                     ...
818                    NaN                 NaN                     NaN
819                    NaN                 NaN                     NaN
820                    NaN            8167.420                     NaN
821                    NaN                 NaN                     NaN
822              20792.607            9907.308               35243.231

     corporate_standard_class  corporate_total  home_office_first_class  \
0                         NaN              NaN                      NaN
1                         NaN              NaN                      NaN
2                         NaN              NaN                      NaN
3                    788.8600         788.8600                      NaN
4                         NaN              NaN                      NaN
..                        ...              ...                      ...
818                   68.7420          68.7420                      NaN
819                       NaN              NaN                      NaN
820                       NaN        8167.4200                      NaN
821                       NaN              NaN                      NaN
822                55942.7865      121885.9325                 7737.786

     home_office_same_day  home_office_second_class  \
0                     NaN                       NaN
1                     NaN                       NaN
2                     NaN                       NaN
3                     NaN                       NaN
4                     NaN                       NaN
..                    ...                       ...
818                   NaN                       NaN
819                   NaN                       NaN
820                   NaN                       NaN
821                   NaN                       NaN
822              2977.456                  8791.127

     home_office_standard_class  home_office_total
0                       91.0560            91.0560
1                           NaN                NaN
2                           NaN                NaN
3                           NaN                NaN
4                           NaN                NaN
..                          ...                ...
818                         NaN                NaN
819                         NaN                NaN
820                         NaN                NaN
821                         NaN                NaN
822                  54748.6325         74255.0015

[823 rows x 16 columns]

TypeError: melt() got an unexpected keyword argument 'ship_m'

In [4]:
df = pd.DataFrame(
...     {
...         "A": {0: "a", 1: "b", 2: "c"},
...         "B": {0: 1, 1: 3, 2: 5},
...         "C": {0: 2, 1: 4, 2: 6},
...     }
... )

pd.melt(df, id_vars=["A"], value_vars=["B"])

   A variable  value
0  a        B      1
1  b        B      3
2  c        B      5

In [9]:
import pandas as pd

shipdf=pd.read_csv("unclean_data_ship.csv")
shipdf.columns = shipdf.columns.str.strip()

print(shipdf.columns.tolist())

shipdf = df.melt(
    id_vars=df.columns[0],  # first column instead of hard-coding
    var_name="Category",
    value_name="Sales"
)

['Order ID', 'consumer_first_class', 'consumer_same_day', 'consumer_second_class', 'consumer_standard_class', 'consumer_total', 'corporate_first_class', 'corporate_same_day', 'corporate_second_class', 'corporate_standard_class', 'corporate_total', 'home_office_first_class', 'home_office_same_day', 'home_office_second_class', 'home_office_standard_class', 'home_office_total']