In [4]:
import pandas as pd
df = pd.DataFrame(
    {"101":["Sales","Mumbai"],
                   "102":["SW","Pune"],
                   "103":["Architects","Chenna"]
                   })

df.describe()
df.columns
df.first
df.last
df.head(2)
df.tail(2)

      101   102         103
0   Sales    SW  Architects
1  Mumbai  Pune      Chenna

In [ ]:
#understand structure of data provided by source(first setep before data cleaning or going further)
import pandas as pd

empdf=pd.read_csv("employees.csv")
print(empdf.describe())
empdf.head(10)#value retrival
print("Shape(Rows:Columns)",empdf.shape)
print("Types:",empdf.dtypes)
print("Information(Rows:Columns)",empdf.info())
print("Columns:",empdf.columns)

#object means the row/column has mixed set of values

              Salary      Bonus %
count    1000.000000  1000.000000
mean    90662.181000    10.207555
std     32923.693342     5.528481
min     35013.000000     1.015000
25%     62613.000000     5.401750
50%     90428.000000     9.838500
75%    118740.250000    14.838000
max    149908.000000    19.944000
Shape(Rows:Columns) (1000, 8)
Types: First Name            object
Gender                object
Start Date            object
Last Login Time       object
Salary                 int64
Bonus %              float64
Senior Management     object
Team                  object
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    object
 2   Start Date         1000 non-null   object
 3   Last Login Time    1000 non-null   object
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object
 7   Team               957 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 62.6+ KB
Information(Rows:Columns) None
Columns: Index(['First Name', 'Gender', 'Start Date', 'Last Login Time', 'Salary',
       'Bonus %', 'Senior Management', 'Team'],
      dtype='object')

In [12]:
empdf.tail(5)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [15]:
print("Shape(Rows:Columns)",empdf.shape)

Shape(Rows:Columns) (1000, 8)

In [24]:
#understand structure o fdata provided by source
empdf = pd.read_csv("employees.csv")
empdf.tail(10)#value retrival
print(empdf.items)

<bound method DataFrame.items of     First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
0      Douglas    Male    8/6/1993        12:42 PM   97308    6.945
1       Thomas    Male   3/31/1996         6:53 AM   61933    4.170
2        Maria  Female   4/23/1993        11:17 AM  130590   11.858
3        Jerry    Male    3/4/2005         1:00 PM  138705    9.340
4        Larry    Male   1/24/1998         4:47 PM  101004    1.389
..         ...     ...         ...             ...     ...      ...
995      Henry     NaN  11/23/2014         6:09 AM  132483   16.655
996    Phillip    Male   1/31/1984         6:30 AM   42392   19.675
997    Russell    Male   5/20/2013        12:39 PM   96914    1.421
998      Larry    Male   4/20/2013         4:45 PM   60500   11.985
999     Albert    Male   5/15/2012         6:24 PM  129949   10.169

    Senior Management                  Team
0                True             Marketing
1                True                   NaN
2               False               Finance
3                True               Finance
4                True       Client Services
..                ...                   ...
995             False          Distribution
996             False               Finance
997             False               Product
998             False  Business Development
999              True                 Sales

[1000 rows x 8 columns]>

In [25]:
import pandas as pd

# Create a DataFrame
df = pd.DataFrame({
    'Name': ['Steve', 'Lia', 'Vin', 'Katie'],
    'Age': [32, 28, 45, 38],
    'Gender': ['Male', 'Female', 'Male', 'Female'],
    'Rating': [3.45, 4.6, 3.9, 2.78]},
    index=['r1', 'r2', 'r3', 'r4'])

# Access the rows of the DataFrame
result = df.index
print('Output Accessed Row Labels:', result)

Output Accessed Row Labels: Index(['r1', 'r2', 'r3', 'r4'], dtype='object')

In [26]:
import pandas as pd

# Create a DataFrame
df = pd.DataFrame({
    'Name': ['Steve', 'Lia', 'Vin', 'Katie'],
    'Age': [32, 28, 45, 38],
    'Gender': ['Male', 'Female', 'Male', 'Female'],
    'Rating': [3.45, 4.6, 3.9, 2.78]},
    index=['r1', 'r2', 'r3', 'r4'])

# Display the Input DataFrame
print('Input DataFrame:\n', df)

# Modify the Row labels of the DataFrame
df.index = [100, 200, 300, 400]
print('Output Modified DataFrame with the updated index labels:\n', df)

Input DataFrame:
      Name  Age  Gender  Rating
r1  Steve   32    Male    3.45
r2    Lia   28  Female    4.60
r3    Vin   45    Male    3.90
r4  Katie   38  Female    2.78
Output Modified DataFrame with the updated index labels:
       Name  Age  Gender  Rating
100  Steve   32    Male    3.45
200    Lia   28  Female    4.60
300    Vin   45    Male    3.90
400  Katie   38  Female    2.78

In [27]:
import pandas as pd

# Create a DataFrame
df = pd.DataFrame({
    'Name': ['Steve', 'Lia', 'Vin', 'Katie'],
    'Age': [32, 28, 45, 38],
    'Gender': ['Male', 'Female', 'Male', 'Female'],
    'Rating': [3.45, 4.6, 3.9, 2.78]},
    index=['r1', 'r2', 'r3', 'r4'])

# Access the column labels of the DataFrame
result = df.columns
print('Output Accessed column Labels:', result)

Output Accessed column Labels: Index(['Name', 'Age', 'Gender', 'Rating'], dtype='object')

In [28]:
import pandas as pd

# Create a DataFrame
df = pd.DataFrame({
    'Name': ['Steve', 'Lia', 'Vin', 'Katie'],
    'Age': [32, 28, 45, 38],
    'Gender': ['Male', 'Female', 'Male', 'Female'],
    'Rating': [3.45, 4.6, 3.9, 2.78]},
    index=['r1', 'r2', 'r3', 'r4'])
    
# Display the Input DataFrame
print('Input DataFrame:\n', df)

# Modify the Column labels of the DataFrame
df.columns = ['Col1', 'Col2', 'Col3', 'Col4']
print('Output Modified DataFrame with the updated Column Labels\n:', df)

Input DataFrame:
      Name  Age  Gender  Rating
r1  Steve   32    Male    3.45
r2    Lia   28  Female    4.60
r3    Vin   45    Male    3.90
r4  Katie   38  Female    2.78
Output Modified DataFrame with the updated Column Labels
:      Col1  Col2    Col3  Col4
r1  Steve    32    Male  3.45
r2    Lia    28  Female  4.60
r3    Vin    45    Male  3.90
r4  Katie    38  Female  2.78

In [ ]:
#https://www.tutorialspoint.com/python_pandas/python_pandas_accessing_dataframe.htm

In [ ]:
import pandas as pd

empdf=pd.read_csv("employees.csv")

#slicing methods for rows
# empdf.iloc[4:12]
# result=empdf.loc[10:15,"First Name"]
# print(result)

#slicing for coloumns with rows

resultcol = empdf.iloc[10:15,3:5] #always in format rows : columns
print(resultcol)

   Last Login Time  Salary
10         9:01 AM   63241
11         3:19 PM  102508
12         1:08 AM  112807
13        11:40 PM  109831
14         7:13 AM   41426

In [37]:

empdf=pd.read_csv("employees.csv")

# Slice a single column
col_A = empdf.loc[:, "First Name"]
print("Slicing a single column A using iloc[]:")
print(col_A)

# Slice multiple columns

cols_AB = empdf.loc[:, "First Name":"Gender"]
print("Slicing multiple columns A and B using iloc[]:")
print(cols_AB)

# sal = empdf.loc[:,"Salary"]
# sum(sal)
# 

bonus = empdf.loc[:,"Bonus %"]
sum(bonus)

Slicing a single column A using iloc[]:
0      Douglas
1       Thomas
2        Maria
3        Jerry
4        Larry
        ...
995      Henry
996    Phillip
997    Russell
998      Larry
999     Albert
Name: First Name, Length: 1000, dtype: object
Slicing multiple columns A and B using iloc[]:
    First Name  Gender
0      Douglas    Male
1       Thomas    Male
2        Maria  Female
3        Jerry    Male
4        Larry    Male
..         ...     ...
995      Henry     NaN
996    Phillip    Male
997    Russell    Male
998      Larry    Male
999     Albert    Male

[1000 rows x 2 columns]

10207.554999999998